services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: portfolio-postgres
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio_db
      TZ: Europe/Rome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio -d portfolio_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: portfolio-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "127.0.0.1:8000:8000"  # Bind to localhost only for security
    environment:
      DATABASE_URL: postgresql://portfolio:portfolio@postgres:5432/portfolio_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      TZ: Europe/Rome
      ENVIRONMENT: production
      LOG_LEVEL: INFO
      ALLOWED_ORIGINS: '["http://localhost:3000"]'
      RUN_MIGRATIONS: "true"
      MIGRATION_TIMEOUT: "300"
      AUTO_ROLLBACK_ON_FAILURE: "false"
      ALPHA_VANTAGE_API_KEY: "57LYM6FMG5QUTTSF"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - portfolio-network
    restart: unless-stopped

  # Celery Worker
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery-worker
    container_name: portfolio-celery-worker
    environment:
      DATABASE_URL: postgresql://portfolio:portfolio@postgres:5432/portfolio_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      TZ: Europe/Rome
      ENVIRONMENT: production
      LOG_LEVEL: INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - portfolio-network
    restart: unless-stopped

  # Celery Beat Scheduler
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery-beat
    container_name: portfolio-celery-beat
    environment:
      DATABASE_URL: postgresql://portfolio:portfolio@postgres:5432/portfolio_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      TZ: Europe/Rome
      ENVIRONMENT: production
      LOG_LEVEL: INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - portfolio-network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "127.0.0.1:3000:3000"  # Bind to localhost only for security
    environment:
      # Runtime backend API URL - used by Next.js API routes for proxying
      BACKEND_API_URL: http://backend:8000
      # Client-side API URL - fallback for client-side API calls
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
      NODE_ENV: production
      DOCKER_ENV: true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  portfolio-network:
    driver: bridge

volumes:
  postgres_data:
    name: portfolio_postgres_data
  redis_data:
    name: portfolio_redis_data
