"""Add wallet_last_sync_time to crypto portfolios

Revision ID: 70a3cd875f27
Revises: a8d9d9aa2246
Create Date: 2025-10-16 11:50:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a3cd875f27'
down_revision: Union[str, None] = 'a8d9d9aa2246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add wallet_last_sync_time column to crypto_portfolios table
    """
    Add an optional `wallet_last_sync_time` column to the `crypto_portfolios` table.

    Adds a nullable `wallet_last_sync_time` column (DateTime) with comment "When the wallet was last successfully synced" to the `crypto_portfolios` table to track wallet synchronization timestamps.
    """
    op.add_column('crypto_portfolios',
        sa.Column('wallet_last_sync_time', sa.DateTime, nullable=True,
                 comment='When the wallet was last successfully synced')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop column
    """
    Reverts the migration by removing the wallet_last_sync_time column from the crypto_portfolios table.
    """
    op.drop_column('crypto_portfolios', 'wallet_last_sync_time')

    # ### end Alembic commands ###
