"""add crypto_portfolio_snapshots table

Revision ID: a8d9d9aa2246
Revises: b2186263afd1
Create Date: 2025-10-14 15:29:33.783554+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d9d9aa2246'
down_revision: Union[str, None] = 'b2186263afd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False, comment='Associated crypto portfolio ID'),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='Date of the snapshot'),
    sa.Column('total_value_eur', sa.Numeric(precision=20, scale=2), nullable=False, comment='Total portfolio value in EUR'),
    sa.Column('total_value_usd', sa.Numeric(precision=20, scale=2), nullable=False, comment='Total portfolio value in USD'),
    sa.Column('total_cost_basis', sa.Numeric(precision=20, scale=2), nullable=False, comment='Total cost basis in portfolio base currency'),
    sa.Column('base_currency', sa.Enum('EUR', 'USD', name='cryptocurrency', native_enum=False), nullable=False, comment='Portfolio base currency (EUR/USD)'),
    sa.Column('holdings_breakdown', sa.String(length=2000), nullable=True, comment='JSON string of holdings breakdown by symbol'),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=4), nullable=True, comment='Total return percentage'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the snapshot was created'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['crypto_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uix_crypto_portfolio_snapshot_date')
    )
    op.create_index(op.f('ix_crypto_portfolio_snapshots_portfolio_id'), 'crypto_portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_crypto_portfolio_snapshots_snapshot_date'), 'crypto_portfolio_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_portfolio_snapshots_snapshot_date'), table_name='crypto_portfolio_snapshots')
    op.drop_index(op.f('ix_crypto_portfolio_snapshots_portfolio_id'), table_name='crypto_portfolio_snapshots')
    op.drop_table('crypto_portfolio_snapshots')
    # ### end Alembic commands ###
