"""Add wallet_address to crypto portfolios

Revision ID: b2186263afd1
Revises: bba8de3622d9
Create Date: 2025-10-09 20:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2186263afd1'
down_revision: Union[str, None] = 'b4c986c7b760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add wallet_address column to crypto_portfolios table
    op.add_column('crypto_portfolios',
        sa.Column('wallet_address', sa.String(length=62), nullable=True,
                 comment='Bitcoin wallet address for paper wallet tracking (optional)')
    )

    # Create index for wallet_address for better query performance
    op.create_index('ix_crypto_portfolios_wallet_address', 'crypto_portfolios',
                   ['wallet_address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index
    op.drop_index('ix_crypto_portfolios_wallet_address', table_name='crypto_portfolios')

    # Drop column
    op.drop_column('crypto_portfolios', 'wallet_address')

    # ### end Alembic commands ###