"""Add wallet_address to crypto portfolios

Revision ID: b2186263afd1
Revises: b4c986c7b760
Create Date: 2025-10-09 20:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2186263afd1'
down_revision: Union[str, None] = 'b4c986c7b760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add wallet_address column to crypto_portfolios table
    """
    Add an optional `wallet_address` column to the `crypto_portfolios` table and create an index on it.
    
    Adds a nullable `wallet_address` column (String(90)) with comment "Bitcoin wallet address for paper wallet tracking (optional)" to the `crypto_portfolios` table, and creates a non-unique index named `ix_crypto_portfolios_wallet_address` on that column to improve query performance.
    """
    op.add_column('crypto_portfolios',
        sa.Column('wallet_address', sa.String(length=90), nullable=True,
                 comment='Bitcoin wallet address for paper wallet tracking (optional)')
    )

    # Create index for wallet_address for better query performance
    op.create_index('ix_crypto_portfolios_wallet_address', 'crypto_portfolios',
                   ['wallet_address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index
    """
    Reverts the migration by removing the wallet_address column and its index from the crypto_portfolios table.
    
    This drops the index named `ix_crypto_portfolios_wallet_address` on `crypto_portfolios` and then drops the `wallet_address` column.
    """
    op.drop_index('ix_crypto_portfolios_wallet_address', table_name='crypto_portfolios')

    # Drop column
    op.drop_column('crypto_portfolios', 'wallet_address')

    # ### end Alembic commands ###