name: Enforce Branch Protection
on:
  pull_request:
    branches:
      - main

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR is from dev
        if: github.base_ref != 'dev'
        run: |
          echo "❌ PRs to main must come from dev branch only"
          exit 1
